import jsPDF from 'jspdf';
import QRCode from 'qrcode';

export const generateCertificate = async (
  url: string,
  version: number,
  timestamp: string,
  suiTxDigest: string,
  contentHash: string,
  walrusBlobId: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // --- HEADER ---
  doc.setFont("times", "bold");
  doc.setFontSize(22);
  doc.text("CERTIFICATE OF DIGITAL AUTHENTICITY", pageWidth / 2, 20, { align: "center" });
  
  doc.setLineWidth(0.5);
  doc.line(20, 25, pageWidth - 20, 25);

  // --- SUBHEADER ---
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by ArchiveChain • Secured by Sui & Walrus", pageWidth / 2, 32, { align: "center" });

  // --- DETAILS BOX ---
  doc.setDrawColor(0);
  doc.setFillColor(248, 250, 252); // Light gray bg
  doc.rect(20, 40, pageWidth - 40, 90, 'F');
  doc.rect(20, 40, pageWidth - 40, 90, 'S');

  const startY = 50;
  const lineHeight = 12;
  const col1 = 30;
  const col2 = 80;

  doc.setTextColor(0);
  doc.setFontSize(12);

  // Row 1: URL
  doc.setFont("helvetica", "bold");
  doc.text("Archived URL:", col1, startY);
  doc.setFont("helvetica", "normal");
  doc.text(url, col2, startY);

  // Row 2: Timestamp
  doc.setFont("helvetica", "bold");
  doc.text("Timestamp (UTC):", col1, startY + lineHeight);
  doc.setFont("helvetica", "normal");
  doc.text(new Date(parseInt(timestamp)).toUTCString(), col2, startY + lineHeight);

  // Row 3: Content Hash
  doc.setFont("helvetica", "bold");
  doc.text("SHA-256 Hash:", col1, startY + lineHeight * 2);
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.text(contentHash.substring(0, 32) + "...", col2, startY + lineHeight * 2);

  // Row 4: Sui Transaction
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Sui Transaction:", col1, startY + lineHeight * 3);
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.text(suiTxDigest, col2, startY + lineHeight * 3);

  // Row 5: Walrus Blob
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Walrus Blob ID:", col1, startY + lineHeight * 4);
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.text(walrusBlobId, col2, startY + lineHeight * 4);

  // --- QR CODE ---
  // Points to the Sui Explorer for verification
  const explorerUrl = `https://suiscan.xyz/testnet/tx/${suiTxDigest}`;
  const qrDataUrl = await QRCode.toDataURL(explorerUrl);
  doc.addImage(qrDataUrl, 'PNG', pageWidth - 70, 90, 30, 30);
  
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Scan to Verify on Blockchain", pageWidth - 55, 125, { align: "center" });

  // --- LEGAL DISCLAIMER ---
  doc.setFont("times", "italic");
  doc.setFontSize(10);
  doc.setTextColor(80);
  const disclaimer = "This document certifies that the content associated with the URL above was cryptographically captured and stored on the decentralized Walrus network. Its integrity is mathematically proven by the Sui blockchain. Any alteration to the source content would result in a mismatched SHA-256 hash.";
  const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 40);
  doc.text(splitDisclaimer, 20, 150);

  // --- FOOTER ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 255);
  doc.text("ARCHIVECHAIN", pageWidth / 2, 280, { align: "center" });

  // Save
  doc.save(`Proof-V${version}-${new Date().toISOString().split('T')[0]}.pdf`);
};
